### ISSUE TITLE
Wrote 0 coins to html/table_2021_02_17.html

### ISSUE THREAD

**Issue by HARiS-HS** [flowcoin/kriptomist#2]
Complete console output:
```
DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/bitcoin/
DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/bitcoin/
ERROR:kriptomist:Skipping bitcoin
Traceback (most recent call last):
  File "kriptomist.py", line 109, in <module>
    coin = Coin(data["slug"], data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
    self.cmc = Coinmarketcap(self.name, data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
    self.init()
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
    self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
KeyError: 'data'
DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/ethereum/
DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/ethereum/
ERROR:kriptomist:Skipping ethereum
Traceback (most recent call last):
  File "kriptomist.py", line 109, in <module>
    coin = Coin(data["slug"], data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
    self.cmc = Coinmarketcap(self.name, data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
    self.init()
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
    self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
KeyError: 'data'
DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/tether/
DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/tether/
ERROR:kriptomist:Skipping tether
Traceback (most recent call last):
  File "kriptomist.py", line 109, in <module>
    coin = Coin(data["slug"], data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
    self.cmc = Coinmarketcap(self.name, data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
    self.init()
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
    self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
KeyError: 'data'
DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/polkadot-new/
DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/polkadot-new/
ERROR:kriptomist:Skipping polkadot-new
Traceback (most recent call last):
  File "kriptomist.py", line 109, in <module>
    coin = Coin(data["slug"], data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
    self.cmc = Coinmarketcap(self.name, data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
    self.init()
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
    self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
KeyError: 'data'
DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/cardano/
DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/cardano/
ERROR:kriptomist:Skipping cardano
Traceback (most recent call last):
  File "kriptomist.py", line 109, in <module>
    coin = Coin(data["slug"], data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
    self.cmc = Coinmarketcap(self.name, data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
    self.init()
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
    self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
KeyError: 'data'
DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/xrp/
DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/xrp/
ERROR:kriptomist:Skipping xrp
Traceback (most recent call last):
  File "kriptomist.py", line 109, in <module>
    coin = Coin(data["slug"], data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
    self.cmc = Coinmarketcap(self.name, data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
    self.init()
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
    self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
KeyError: 'data'
DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/binance-coin/
DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/binance-coin/
ERROR:kriptomist:Skipping binance-coin
Traceback (most recent call last):
  File "kriptomist.py", line 109, in <module>
    coin = Coin(data["slug"], data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
    self.cmc = Coinmarketcap(self.name, data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
    self.init()
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
    self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
KeyError: 'data'
DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/litecoin/
DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/litecoin/
ERROR:kriptomist:Skipping litecoin
Traceback (most recent call last):
  File "kriptomist.py", line 109, in <module>
    coin = Coin(data["slug"], data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
    self.cmc = Coinmarketcap(self.name, data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
    self.init()
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
    self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
KeyError: 'data'
DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/chainlink/
DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/chainlink/
ERROR:kriptomist:Skipping chainlink
Traceback (most recent call last):
  File "kriptomist.py", line 109, in <module>
    coin = Coin(data["slug"], data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
    self.cmc = Coinmarketcap(self.name, data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
    self.init()
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
    self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
KeyError: 'data'
DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/bitcoin-cash/
DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/bitcoin-cash/
ERROR:kriptomist:Skipping bitcoin-cash
Traceback (most recent call last):
  File "kriptomist.py", line 109, in <module>
    coin = Coin(data["slug"], data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
    self.cmc = Coinmarketcap(self.name, data=data)
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
    self.init()
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
    self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
KeyError: 'data'
INFO:util:Wrote 0 coins to html/table_2021_02_17.html
INFO:util:Wrote 0 coins to html/coinbasepro_table_2021_02_17.html
INFO:util:Wrote 0 coins to html/binance_table_2021_02_17.html
INFO:util:Wrote 0 coins to html/bitstamp_table_2021_02_17.html
Traceback (most recent call last):
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002426EE592B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.livecoin.net', port=443): Max retries exceeded with url: /exchange/ticker (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002426EE592B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kriptomist.py", line 118, in <module>
    supported = Ex.prices()
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\livecoin.py", line 13, in prices
    data = cls.request(cls.URL_PRICES)
  File "C:\Users\HARiS\Desktop\Kriptomist\sources\exchange.py", line 10, in request
    return requests.get(url).json()
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.livecoin.net', port=443): Max retries exceeded with url: /exchange/ticker (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002426EE592B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by Ziinax** [comment]
> Complete console output:
> 
> ```
> DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/bitcoin/
> DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/bitcoin/
> ERROR:kriptomist:Skipping bitcoin
> Traceback (most recent call last):
>   File "kriptomist.py", line 109, in <module>
>     coin = Coin(data["slug"], data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
>     self.cmc = Coinmarketcap(self.name, data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
>     self.init()
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
>     self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
> KeyError: 'data'
> DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/ethereum/
> DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/ethereum/
> ERROR:kriptomist:Skipping ethereum
> Traceback (most recent call last):
>   File "kriptomist.py", line 109, in <module>
>     coin = Coin(data["slug"], data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
>     self.cmc = Coinmarketcap(self.name, data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
>     self.init()
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
>     self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
> KeyError: 'data'
> DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/tether/
> DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/tether/
> ERROR:kriptomist:Skipping tether
> Traceback (most recent call last):
>   File "kriptomist.py", line 109, in <module>
>     coin = Coin(data["slug"], data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
>     self.cmc = Coinmarketcap(self.name, data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
>     self.init()
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
>     self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
> KeyError: 'data'
> DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/polkadot-new/
> DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/polkadot-new/
> ERROR:kriptomist:Skipping polkadot-new
> Traceback (most recent call last):
>   File "kriptomist.py", line 109, in <module>
>     coin = Coin(data["slug"], data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
>     self.cmc = Coinmarketcap(self.name, data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
>     self.init()
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
>     self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
> KeyError: 'data'
> DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/cardano/
> DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/cardano/
> ERROR:kriptomist:Skipping cardano
> Traceback (most recent call last):
>   File "kriptomist.py", line 109, in <module>
>     coin = Coin(data["slug"], data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
>     self.cmc = Coinmarketcap(self.name, data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
>     self.init()
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
>     self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
> KeyError: 'data'
> DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/xrp/
> DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/xrp/
> ERROR:kriptomist:Skipping xrp
> Traceback (most recent call last):
>   File "kriptomist.py", line 109, in <module>
>     coin = Coin(data["slug"], data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
>     self.cmc = Coinmarketcap(self.name, data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
>     self.init()
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
>     self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
> KeyError: 'data'
> DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/binance-coin/
> DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/binance-coin/
> ERROR:kriptomist:Skipping binance-coin
> Traceback (most recent call last):
>   File "kriptomist.py", line 109, in <module>
>     coin = Coin(data["slug"], data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
>     self.cmc = Coinmarketcap(self.name, data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
>     self.init()
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
>     self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
> KeyError: 'data'
> DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/litecoin/
> DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/litecoin/
> ERROR:kriptomist:Skipping litecoin
> Traceback (most recent call last):
>   File "kriptomist.py", line 109, in <module>
>     coin = Coin(data["slug"], data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
>     self.cmc = Coinmarketcap(self.name, data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
>     self.init()
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
>     self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
> KeyError: 'data'
> DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/chainlink/
> DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/chainlink/
> ERROR:kriptomist:Skipping chainlink
> Traceback (most recent call last):
>   File "kriptomist.py", line 109, in <module>
>     coin = Coin(data["slug"], data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
>     self.cmc = Coinmarketcap(self.name, data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
>     self.init()
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
>     self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
> KeyError: 'data'
> DEBUG:fetcher:Not in cache: https://coinmarketcap.com/currencies/bitcoin-cash/
> DEBUG:fetcher:Stored to cache: https://coinmarketcap.com/currencies/bitcoin-cash/
> ERROR:kriptomist:Skipping bitcoin-cash
> Traceback (most recent call last):
>   File "kriptomist.py", line 109, in <module>
>     coin = Coin(data["slug"], data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\coin.py", line 29, in __init__
>     self.cmc = Coinmarketcap(self.name, data=data)
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 43, in __init__
>     self.init()
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\coinmarketcap.py", line 61, in init
>     self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
> KeyError: 'data'
> INFO:util:Wrote 0 coins to html/table_2021_02_17.html
> INFO:util:Wrote 0 coins to html/coinbasepro_table_2021_02_17.html
> INFO:util:Wrote 0 coins to html/binance_table_2021_02_17.html
> INFO:util:Wrote 0 coins to html/bitstamp_table_2021_02_17.html
> Traceback (most recent call last):
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
>     conn = connection.create_connection(
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno 11001] getaddrinfo failed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
>     httplib_response = self._make_request(
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
>     self._validate_conn(conn)
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
>     conn.connect()
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 353, in connect
>     conn = self._new_conn()
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002426EE592B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
>     retries = retries.increment(
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 573, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.livecoin.net', port=443): Max retries exceeded with url: /exchange/ticker (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002426EE592B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "kriptomist.py", line 118, in <module>
>     supported = Ex.prices()
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\livecoin.py", line 13, in prices
>     data = cls.request(cls.URL_PRICES)
>   File "C:\Users\HARiS\Desktop\Kriptomist\sources\exchange.py", line 10, in request
>     return requests.get(url).json()
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 76, in get
>     return request('get', url, params=params, **kwargs)
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Users\HARiS\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.livecoin.net', port=443): Max retries exceeded with url: /exchange/ticker (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002426EE592B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
> ```

Have the same problem here it comes from the file Coinmarketcap.py when fetching coins, 
        self.id = list(d['props']['initialState']['cryptocurrency']['info']['data'].keys())[0]
"info" doesn't contain "data".
